# Generated by Django 5.2.10 on 2026-02-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_decription_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
